name: experthub_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
        - asset: assets/fonts/Sarabun-Thin.ttf
