// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5UYza208G5RXUzvItdqC3-wcCF5Ir8E',
    appId: '1:910339715304:android:87d05a16b9973eb640595d',
    messagingSenderId: '910339715304',
    projectId: 'experthub-a29d5',
    databaseURL: 'https://experthub-a29d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'experthub-a29d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9afQVH9j-L2TBH7ZyH3s_tLr15sQ78Bs',
    appId: '1:910339715304:ios:98c700271c962cf640595d',
    messagingSenderId: '910339715304',
    projectId: 'experthub-a29d5',
    databaseURL: 'https://experthub-a29d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'experthub-a29d5.appspot.com',
    iosBundleId: 'com.example.experthubApp',
  );
}
